name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        # specifically for mysql
        env:  
          MYSQL_DATABASE: django_db
          MYSQL_USER: django_db_user
          MYSQL_PASSWORD: django_db_password
          MYSQL_ROOT_PASSWORD: django_db_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install MySQL client and Run Tests
      run: |
        sudo apt-get install -y default-mysql-client
        python manage.py migrate
        python manage.py test
