name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        # specifically for mysql
        env:  
          MYSQL_DATABASE: django_db
          MYSQL_USER: django_db_user
          MYSQL_PASSWORD: django_db_password
          MYSQL_ROOT_PASSWORD: django_db_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Service Account JSON from GCP Secret Manager
      run: |
        gcloud secrets versions access latest --secret=django_hosting_json_file --project=django-hosting-427421 > gcp-key.json

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project django-hosting-427421

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

    - name: Install MySQL client and Run Tests
      env:
        DATABASE_URL: mysql://django_db_user:django_db_password@localhost:3306/django_db
      run: |
        sudo apt-get install -y default-mysql-client
        python manage.py migrate
        python manage.py test
