jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCP credentials
        run: |
          echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > gcp_credentials.json
          # Debugging: Show the first 100 characters of the credentials file (safe for debugging)
          head -n 1 gcp_credentials.json
          
      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=gcp_credentials.json
